NULL

#' Splice junction coordinates and read support for select genomic regions of TCGA samples
#' Splice junction details derived using the STAR alignment algorithm, specificaly the SJ.tab tables generated by STAR
#'
#' The following items get loaded up:
#'   gbm3=a glioblastoma sample from TCGA with SJ details (chr,start,end and uniq.reads=number of uniquely mapped split reads) for select genomic regions in chr6, chr9 and chr12
#'   gbm3.vcf=toy mutation file in bed format with mutations supposedly associated with the sample gbm3
#'   GBM=list of 3 glioblastoma samples from TCGA that are outputs from the SCANVIS.scan and SCANVIS.linkvar functions
#'   LUSC=list of 2 lung squamous cell carcinoma samples from TCGA (portions thereof) that are outputs of the SCANVIS.scan function and is referenced in documentation for visualization functions
#'   LUAD=list of 3 lung adenocarcinoma TCGA samples (portions thereof) that are outputs of SCANVIS.scan and is referenced for visualization functiions
"SCANVIS_examples"
