NULL

#' Splice junction coordinates and read support for select genomic 
#' regions of TCGA samples
#' Splice junction details derived using the STAR alignment algorithm, 
#' specificaly the SJ.tab tables generated by STAR
#'
#' The following items get loaded up:
#'   gen19=select portions from the full gencode19 object generated by 
#'         SCANVISannotation obtained by the following url:
#'         ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/ 
#'   gbm3=select parts of a TCGA glioblastoma sample in SCANVIS format
#'	  Format is chr,start,end and uniq.reads where
#'                     uniq.reads = number of uniquely mapped split reads
#'   gbm3.vcf=toy mutation file for gbm3 in bed format
#'   GBM=list of 3 TCGA glioblastoma partial outputs from SCANVISscan/linkvar
#'   LUSC=list of 2 TCGA lung squamous cell carcinoma partial outputs 
#'        from SCANVISscan/linkvar
#'   LUAD=list of 3 TCGA lung adenocarcinoma partial outputs 
#'        from SCANVISscan/linkvar 
"SCANVISexamples"
